//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOHEv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate_type
    {
        public int Certificate_type_id { get; set; }
        public Nullable<int> Certificate_type_code { get; set; }
        public string Certificate_type_name { get; set; }
    }
}
