//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOHEv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_kind
    {
        public int From_kind_id { get; set; }
        public Nullable<int> From_kind_code { get; set; }
        public string From_kind_name { get; set; }
    }
}
