//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOHEv2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mohedbEntities1 : DbContext
    {
        public mohedbEntities1()
            : base("name=mohedbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academy_type> Academy_type { get; set; }
        public virtual DbSet<Certificate_type> Certificate_type { get; set; }
        public virtual DbSet<Form_kind> Form_kind { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
