//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOHEv2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Transaction
    {
        public int trans_id { get; set; }
        public string Source_trans_id { get; set; }
        [Display(Name = "—ﬁ„ «·Ã·Ê”")]
        public string Student_num { get; set; }
        public string Student_name { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> From_kind_code { get; set; }
        public Nullable<int> academy_type_code { get; set; }
        public Nullable<int> Certificate_type_code { get; set; }
        public Nullable<System.DateTime> Trans_date { get; set; }
        public string e15 { get; set; }
        public Nullable<int> user_code { get; set; }
        public string StNo { get; set; }
        public string FormNo { get; set; }
    }
}
