//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOHEv2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class user
    {
        public int user_id { get; set; }
        
        [Display(Name = "ÇÓã ÇáİÑÚ")]
        public string Branch_name { get; set; }
        [Display(Name = "ßæÏ ÇáİÑÚ")]
        public string Branch_code { get; set; }
        [Display(Name = "ÇáÕáÇÍíå")]
        public string Privilege { get; set; }
        [Display(Name = "ÇáÑŞã ÇáÓÑí")]
        public string password { get; set; }
        public string loginerr { get; set; }

    }
}
